services:
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    envVars:
      - key: PORT
        value: "6000" # Render automatically sets PORT; this is optional
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
